---
title: "Processing eReefs data {{< fa brands python >}}"
---

# Motivating problem

In this example we use eReefs time series data to try answer the question:

**_How strong does the wind need to be to set the direction of the surface ocean currents?_**

We use the [AIMS eReefs extraction tool](https://extraction.ereefs.aims.gov.au/) to extract data for two locations of interest:

* Myrmidon Reef which is on the far outer edge of the GBR and is almost right in the middle of the southern Eastern Australian Current; and

* Davies Reef which is further in the reef matrix, but in a similar sector of the GBR.

We then process the data and investigate the relationship between the strength of the wind and the direction of the surface currents for two locations. 


# Analysis method

The East Australian Current (EAC) usually is a strong southward current near Myrmidon and Davies Reefs. During winter months the wind moves in a north eastern direction in the near opposite direction to the EAC. When the wind is low the surface currents are dominated by the EAC. As the wind picks up at some speed the wind overpowers the EAC and the surface current moves in the direction of the wind.

To determine the relation between the wind and the surface currents we will use the AIMS eReefs extraction tool to pull out hourly time series wind and current data for our two locations of interest. We will then look at the correlation between the wind and current vectors, where a correlation of 1 indicates they are pointing in the same direction, and -1 indicated they are in opposite directions.


# Setting up to get the data

To extract the time series data using the extraction tool we need to create a CSV file containing the sites of interest. This file needs to contain the coordinates and names of the sites. To create this I first added my points manually in Google Earth Pro. This was done to simply get the location of Myrmidon and Davies Reefs. Using Google Earth to create your CSV file for the extraction tool is only useful if you don't already know the coordinates of your sites.


[Screenshot of Google Earth Pro with Myromidon and Davies reef sites](images/google-earth-reef-locatons.jpg)

The points can be added using the `Add placemark` tool (looks like a pin). The locations can be seen by displaying the placemark properties. The resulting KML file can be found [here](resources/extraction-tool-locations.kml).

The location of the two sites were copied to create the [CSV file for the data extraction tool](resources/site_coordinates.csv).


# Extracting the data

The CSV file was uploaded to the [AIMS extraction tool](https://extraction.ereefs.aims.gov.au/) and the extraction was performed with the following settings: 

* *Data collection*: GBR1 Hydro (Version 2) 

* *Variables*: 
    - Eastward wind speed (`wspeed_u`)
    - Northward wind speed (`wspeed_v`)
    - Northward current (`v`)
    - Eastward current (`u`) 

* *Date range*: 1 January 2019 - 31 December 2019 

* *Time step*: hourly 

* *Depths*: -2.35 m

Once the extraction request was submitted the dataset was created after an one hour of processing the data was available for download from [Extraction request: Example dataset: Wind-vs-Current at Davies and Myrmidon Reefs (2019)](https://extraction.ereefs.aims.gov.au/data/2009.c451dc3).

# Downloading the data

In this notebook we will download the data using scripting. There is no need to re-run the extraction request as each extraction performed by the extraction tool has a permanent public page created for it that can be used to facilitate sharing of the data.

Let's first create a temporary folder to contain the downloaded data. Note: The temp folder is excluded using the .gitignore so it is not saved to the code repository, which is why we must reproduce it.

```{python}
import os
if not os.path.exists('temp'):
    os.makedirs('temp')
```

Now let's download the data. The file to download is 12.9 MB and so this download might take a little while. To allow us to re-run this script without having to wait for the download each time we first check that the download has not already been done.

```{python}
import urllib.request
extractionfile = os.path.join('temp','2009.c451dc3-collected.csv')  # Use os.path.join so the script will work cross-platform

if not os.path.exists(extractionfile):
    print("Downloading extraction data ...")
    url = 'https://api.ereefs.aims.gov.au/data-extraction/request/2009.c451dc3/files/2009.c451dc3-collected.csv'
    req = urllib.request.urlretrieve(url, extractionfile)
    print(req)
else:
    print("Skipping redownloading extraction data")
```


# Reading and cleaning the data

Read the resulting CSV file into a [Pandas data frame](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html).

```{python}
import pandas as pd
df = pd.read_csv(extractionfile)
df.head()
```

Here we can see that data is in [tidy format](https://towardsdatascience.com/whats-tidy-data-how-to-organize-messy-datasets-in-python-with-melt-and-pivotable-functions-5d52daa996c9). That is each observation is in one row per time step, variable, depth and site. For each of these combinations there are summary statistics corresponding to the aggregation process that was applied. Somewhat confusingly we extracted hourly data from the hourly eReefs hydrodynamic model and so there was no aggregation applied. As a result all the stats values are the same and the mean corresponds to the actual extracted data values. Let's clean this up a little by removing the redundant columns. Here we also drop the depth variable as the depth of the wind doesn't match the depth of the surface current and so makes it difficult to align the wind and the current together. Since we are only processing a single depth this is an OK simplification. If we were processing the current at multiple depths then we would need a more complex set of data wraggling.


```{python}
df2 = df.drop(columns=['median', 'p5', 'p95', 'lowest','highest','Depth']).rename(columns={"mean": "value"})
df2.head()
```

Next we need to align the wind and current values for a given time step and site on to the same rows of data. Here we are converting the data from tall format to wide format.

```{python}
df3 = df2.pivot(index = ["Site Name", "Latitude", "Longitude", "Aggregated Date/Time", ], columns="Variable", values="value")
df3.head()
```

Our aim is to create an index that estimates the correlation of the current and the wind vectors.

The correlation of the current and wind vectors can be estimated based using the [dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html). An overview of the relationship between correlation and using the dot product is described in [Geometric Interpretation of the Correlation between Two Variables](https://medium.com/@ns2586/geometric-interpretation-of-the-correlation-between-two-variables-4011fb3ea18e). The correlation between the two vectors is given by:

$$
r = \cos(\theta) = \frac{a \cdot b}{||a||\cdot||b||}
$$
 

where $a \cdot b$ is the dot product between the two vectors and $||a||$ and $||b||$ are the magnitudes of the vectors. The dot product can be calculated as

$$
a \cdot b = a_x \times b_x + a_y \times b_y
$$

and the magnitude of the vectors as

$$
||a|| = \sqrt{a^2_x + a^2_y} \;\;, \; \;\;\;\; 
||b|| = \sqrt{b^2_x + b^2_y}
$$

```{python}
import numpy as np
df3['currentmag'] = np.sqrt(df3['u']**2+df3['v']**2)
df3['windmag'] = np.sqrt(df3['wspeed_u']**2+df3['wspeed_v']**2)
df3['windcurrentcorr'] = (df3['u'] * df3['wspeed_u'] + df3['v'] * df3['wspeed_v'])/(df3['currentmag']*df3['windmag'])
df3.head()
```


Let's look at the relationship between the wind and current as a function of the wind speed. Here we are considering each hourly sample as an independent estimate of the relationship. In reality this is not the case as the longer the wind blows the more effect it will have on the current. As this is just a coding example and not an in-depth analysis we don't need to worry about this limitation of the analysis.

Let's pull out the data for Davies and Myrmidon Reefs separately so they are easy to plot.

```{python}
davies = df3.query('`Site Name` == "Davies Reef"')
myrmidon = df3.query('`Site Name` == "Myrmidon Reef"')
myrmidon.head()
```

Let's create a scatter plot to see if there is a relationship between the wind and currents.

```{python}
import matplotlib.pyplot as plt
fig = plt.figure()
ax=fig.add_axes([0,0,1,1])
ax.scatter(myrmidon["windmag"],myrmidon["windcurrentcorr"], color='r', s=1)
ax.scatter(davies["windmag"],davies["windcurrentcorr"], color='b', s=1)
ax.set_xlabel('Wind speed (m/s)')
ax.set_ylabel('Wind-current correlation')
ax.set_title('Correlation between wind and surface current (hourly data, 2019)')
```

This scatter plot shows that the relationship between wind and current is weak. This is not surprising given that we are considering just the hourly samples, with no consideration for how long the wind has been blowing. At low wind conditions the current has an even chance of being aligned with the wind (correlation $r= 1$) as in the opposite direction (correlation $r= -1$), however in high wind we can see that there is much more chance that the currents are aligned with the wind.

To understand this relationship better we want to understand how much the wind nudges the current in its direction. If we bin the wind speeds then collect all the correlation samples in each bin then we can see if they average to zero (indicating that there is no relationship between the wind and current) or there is average alignment.

```{python}
from scipy import stats
wind = davies["windmag"]
current = davies["windcurrentcorr"]
bin_means, bin_edges, binnumber = stats.binned_statistic(wind, current, 'mean', bins=20)
plt.hlines(bin_means, bin_edges[:-1], bin_edges[1:], colors='g', lw=5,
           label='Davies Reef')

wind = myrmidon["windmag"]
current = myrmidon["windcurrentcorr"]
bin_means, bin_edges, binnumber = stats.binned_statistic(wind, current, 'mean', bins=20)
plt.hlines(bin_means, bin_edges[:-1], bin_edges[1:], colors='r', lw=5,
           label='Myrmidon Reef')

plt.xlabel('Wind speed (m/s)')
plt.ylabel('Wind-current correlation')
plt.title('Mean correlation between wind and surface current (hourly data, 2019)')
plt.legend()
```

From this we can see that for wind speeds below 8 m/s the surface current direction is unrelated to the wind. Above this wind speed the surface current is increasingly determined by the direction of the wind. By the time the wind is 16 m/s the direction of the surface current is dominated by the wind direction.

> *Note*: It should be remembered that this analysis is based on the eReefs Hydrodynamic model and as such is not based on real data. The eReefs model has however been tuned to accurately capture the flow dynamics of the GBR and so we would expect the estimates from this analysis to be approximately correct.
