project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  title: "eReefs tutorials"
  navbar: 
    background: "#ffffff"
    logo: images/ereefs_aims_logo.png
    left: 
      - href: tutorials/r/r_tutorials_homepage.qmd
        text: "{{< fa brands r-project >}}"
      - href: tutorials/python/python_tutorials_homepage.qmd
        text: "{{< fa brands python >}} python"

    right:
      - text: "   "
      - href: "https://github.com/bfordAIMS/ereefs-tutorials"
        icon: "github"
    collapse-below: sm

format:
  html:
    theme: 
      light: [flatly, theme_changes_light.scss]
      dark: [darkly, theme_changes_dark.scss]
    highlight-style: atom-one
    css: styles.css
    toc: true

execute:
  freeze: auto
  code-fold: true

