project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  title: "AIMS eReefs tutorials"
  navbar: 
    background: "#4a85b4"
    logo: images/logo.png
    right:
      - href: r_tutorials_home.qmd
        text: "{{< fa brands r-project >}}"
      - href: python_tutorials_home.qmd
        text: "{{< fa brands python >}} Python"
    collapse-below: sm

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    highlight-style: atom-one
    css: styles.css
    toc: true



